CREATE TABLE IF NOT EXISTS USERS
(
    ID BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    LOGIN varchar(50) NOT NULL UNIQUE,
    PASSWORD varchar(100),
    FIRST_NAME varchar(100) NOT NULL,
    LAST_NAME varchar(100),
    EMAIL varchar(150) NOT NULL UNIQUE,
    DATE_CREATE timestamp,
    DATE_BLOCK timestamp,
    DATE_LAST_ONLINE timestamp,
    ROLE varchar(32),
    STATUS varchar(32)
);

CREATE TABLE IF NOT EXISTS CATEGORIES
(
  ID BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
  NAME varchar(100) NOT NULL UNIQUE,
  DATE_CREATE timestamp,
  DATE_CLOSE timestamp
);

CREATE TABLE IF NOT EXISTS ARTICLES
(
    ID BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    TITLE varchar(300) NOT NULL,
    CONTENT varchar(4000) NOT NULL,
    DATE_CREATE timestamp,
    DATE_CLOSE timestamp,
    STATUS varchar(32),
    AUTHOR_ID BIGINT,
    CATEGORY_ID BIGINT,
    CONSTRAINT ARTICLES_USERS_ID_FK FOREIGN KEY (AUTHOR_ID) REFERENCES USERS (ID) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT ARTICLES_CATEGORIES_ID_FK FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORIES (ID) ON DELETE SET NULL ON UPDATE CASCADE
);